HaveYouSeenMe/HaveYouSeenMe/Models/Message.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaveYouSeenMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public int UserId { get; set; }
        public System.DateTime MessageDate { get; set; }
        public string From { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message1 { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}

HaveYouSeenMe/HaveYouSeenMe/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HaveYouSeenMe.Models;

namespace HaveYouSeenMe.Controllers
{
    public class MessageController : Controller
    {
        //
        // GET: /Message/

        public ActionResult Send()
        {
            var name = (string)RouteData.Values["id"];
            ViewBag.PetName = name;
            ViewBag.IsSent = false;
            return View();
        }

        [HttpPost]
        public ActionResult Send(MessageModel model)
        {
            if (string.IsNullOrEmpty(model.From))
            {
                ModelState.AddModelError("From", "The From field is required.");
            }
            if (string.IsNullOrEmpty(model.Email))
            {
                ModelState.AddModelError("Email", "The Email field is required.");
            }
            if (string.IsNullOrEmpty(model.Message))
            {
                ModelState.AddModelError("Message", "The Message field is required.");

            }
            if (ModelState.IsValid)
            {
                return RedirectToAction("Thankyou");
            }
            ModelState.AddModelError("", "One or more errors were fond");
            return View(model);
        }
        public PartialViewResult Thankyou()
        {
            return PartialView();
        }

    }
}

HaveYouSeenMe/HaveYouSeenMe/Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HaveYouSeenMe.Models;
using System.IO;
using HaveYouSeenMe.Models.Business;
namespace HaveYouSeenMe.Controllers
{
    public class PetController : Controller
    {
        //public ActionResult Display()
        //{
        //    var name = (string)RouteData.Values["id"];
        //    var model = PetManagement.GetByName(name);
        //    if (model == null)
        //    {
        //        return RedirectToAction("NotFound");
        //    }
        //    return View(model);
        //}
        public ActionResult NotFound()
        {
            return View();
        }
        public FileResult DownloadPetPicture() 
        {
            var name = (string)RouteData.Values["id"];
            var picture = "/Content/Uploads/" + name + ".jpg";
            var contentTyped = "image/jpg";
            var fileName = name + ".jpg";
            return File(picture,contentTyped,fileName);
        }
        // Using HttpStatusCodeResult
        public HttpStatusCodeResult UnauthorizedError()
        {
            return new HttpUnauthorizedResult("Custom Unauthorized Error");
        }
        // Using HttpNotFoundResult

        public ActionResult NotFoundError()
        {
            return HttpNotFound("Nothing here....");
        }
        public ActionResult PictureUpload()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PictureUpload(PictureModel model)
        {
            if (model.PictureFile.ContentLength > 0)
            {
                var fileName = Path.GetFileName(model.PictureFile.FileName);
                var filePath = Server.MapPath("/Content/Uploads");
                string savedFileName = Path.Combine(filePath, fileName);
                model.PictureFile.SaveAs(savedFileName);
                PetManagement.CreateThumbnails(fileName, filePath, 100, 100, true);
            }
            return View(model);
        }

        public ActionResult GetPhoto()
        {
            var name = (string)RouteData.Values["id"];
            ViewBag.Photo = string.Format("/Content/Uploads/{0}.jpg", name);
            return PartialView();
        }
       

    }
}

HaveYouSeenMe/HaveYouSeenMe/Views/Message/Send.cshtml
@model HaveYouSeenMe.Models.MessageModel
@{
    ViewBag.Tittle = "Send";
}
<div id="messageForm">
    <h2>Send Message</h2>
    @using (Ajax.BeginForm(new AjaxOptions
    {
        Confirm = "Are you sure want to send this message?",
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        LoadingElementId = "loading",
        UpdateTargetId = "messageForm",
        OnBegin = "beginRequest",
        OnComplete = "endRequest"
    }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <fieldset>
            <legend>MessageModel</legend>

            <div class="editor-label">
                @Html.LabelFor(model => model.From)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.From)
                @Html.ValidationMessageFor(model => model.From)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Email)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Subject)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Subject)
                @Html.ValidationMessageFor(model => model.Subject)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.Message)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Message)
                @Html.ValidationMessageFor(model => model.Message)
            </div>
            <p>
                <input type="submit" value="Send Message" />
            </p>

        </fieldset>
    }
</div>

<div id="loading" style="display:none">
    Send Message...
</div>

<div id="petPhoto">
    @*@Ajax.ActionLink("Display pet picture", "GetPhoto", "Pet",
            new RouteValueDictionary { { "id", ViewBag.PetName} },
            new AjaxOptions {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,
                LoadingElementId = "loadingPhoto",
                UpdateTargetId = "petPhoto"

            })*@
    <a href="#" id="getPhoto">Display pet picture</a>
</div>
<div id="loadingPhoto" style="display:none">
    Loading Pet...
</div>
<img src="@ViewBag.Photo" style="width:150px;height:150px"/>
<div>
    @Html.ActionLink("Back to List", "Index");
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        function beginRequest() {
            $("messageForm").hide();
        }
        function endRequest() {
            $("messageForm").show();
        }
    </script>
    <script>
        $(document).ready(function () {
            $("#getPhoto").on("click", function (e) {
                e.preventDefault();
                $.ajax({
                    url: "Pet/GetPhoto/dog",
                    type: "POST",
                    dataType: "html",
                    beforeSend: function () {
                        $("#loadingPhoto").show();
                    },
                    complete: function () {
                        $("#loadingPhoto").hide();
                    },
                    success: function () {
                        $("#petPhoto").html(data);
                    }
                });
            });
        });
    </script>
}

HaveYouSeenMe/HaveYouSeenMe/Views/Message/Thankyou.cshtml
@{
    ViewBag.Tittle = "Thanks you";
}

<h2>Thank You</h2>
<p>Your message has been sent</p>